import { Inter } from 'next/font/google'
import './globals.css'
import ResponsiveAppBar from './component/header'
import Footer from './component/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
        <ResponsiveAppBar />
        {children}
        <Footer />
      </body>

    </html>
  )
}
// const RootLayout = ({ children }) => {
//   return (
//     <html lang="en">
//       <head>
//         {/* Add font import */}
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" />
//         {/* Add metadata */}
//         <title>{metadata.title}</title>
//         <meta name="description" content={metadata.description} />
//         {/* Add other meta tags or dependencies */}
//       </head>
//       <body>
//         <ResponsiveAppBar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// };

// export default RootLayout;